/* =========================================================================
 *  levels.js  —  6 "глобальних" рівнів: від мікросвіту до космосу.
 *  Кожен рівень закінчується босом-вченим, якого треба з'їсти.
 * ========================================================================= */

const LEVELS = [
  {
    id: 1,
    name: 'РІВЕНЬ 1 — ЛАБОРАТОРІЯ',
    subtitle: 'Нікіта втік із пробірки...',
    world: 2200,
    startR: 9,
    bossR: 70,
    boss: 'egor',
    bossShoots: false,
    sky: ['#10324a', '#06121e'],
    grid: 'rgba(90,180,220,0.07)',
    floor: '#0c2335',
    hue: 285,
    spawns: [
      { type: 'microbe', count: 120, rMin: 4, rMax: 10 },
      { type: 'atom', count: 70, rMin: 6, rMax: 13 },
      { type: 'pill', count: 55, rMin: 10, rMax: 20 },
      { type: 'beaker', count: 36, rMin: 18, rMax: 34 },
      { type: 'mouse', count: 22, rMin: 26, rMax: 48 },
    ],
    tips: 'Рухай мишкою (або WASD). Їж усе, що менше за тебе — і рости!',
  },
  {
    id: 2,
    name: 'РІВЕНЬ 2 — КАБІНЕТ ВЧЕНИХ',
    subtitle: 'Нікіта виліз на стіл...',
    world: 2700,
    startR: 12,
    bossR: 82,
    boss: 'danya',
    bossShoots: false,
    sky: ['#3a2f4a', '#1a1422'],
    grid: 'rgba(255,210,160,0.05)',
    floor: '#6b5436',
    hue: 285,
    spawns: [
      { type: 'microbe', count: 40, rMin: 5, rMax: 11 },
      { type: 'mug', count: 50, rMin: 14, rMax: 26 },
      { type: 'book', count: 60, rMin: 16, rMax: 30 },
      { type: 'plant', count: 34, rMin: 24, rMax: 42 },
      { type: 'laptop', count: 30, rMin: 30, rMax: 50 },
      { type: 'chair', count: 22, rMin: 40, rMax: 60 },
    ],
    tips: 'Більший Нікіта = більша їжа. Маленьке тепер на один зубок!',
  },
  {
    id: 3,
    name: 'РІВЕНЬ 3 — ВУЛИЦЯ МІСТА',
    subtitle: 'Нікіта вибрався надвір...',
    world: 3200,
    startR: 16,
    bossR: 98,
    boss: 'pilipyuk',
    bossShoots: false,
    sky: ['#5a86b0', '#2e4d6e'],
    grid: 'rgba(255,255,255,0.05)',
    floor: '#4a5560',
    hue: 285,
    spawns: [
      { type: 'hydrant', count: 30, rMin: 16, rMax: 26 },
      { type: 'bench', count: 28, rMin: 22, rMax: 34 },
      { type: 'person', count: 40, rMin: 22, rMax: 36 },
      { type: 'tree', count: 44, rMin: 30, rMax: 52 },
      { type: 'car', count: 40, rMin: 40, rMax: 64 },
    ],
    tips: 'Перехожі-вчені тікають! Наздожени та проковтни.',
  },
  {
    id: 4,
    name: 'РІВЕНЬ 4 — МЕГАПОЛІС',
    subtitle: 'Нікіта розміром із будинок...',
    world: 3700,
    startR: 22,
    bossR: 116,
    boss: 'dima',
    bossShoots: false,
    sky: ['#243b6e', '#0e1730'],
    grid: 'rgba(150,180,255,0.05)',
    floor: '#2a3450',
    hue: 285,
    spawns: [
      { type: 'car', count: 40, rMin: 20, rMax: 34 },
      { type: 'tree', count: 36, rMin: 26, rMax: 40 },
      { type: 'person', count: 24, rMin: 18, rMax: 28 },
      { type: 'house', count: 34, rMin: 44, rMax: 66 },
      { type: 'building', count: 30, rMin: 60, rMax: 92 },
    ],
    tips: 'Цілі будинки зникають у пащі. Місто не врятувати!',
  },
  {
    id: 5,
    name: 'РІВЕНЬ 5 — НАД КОНТИНЕНТОМ',
    subtitle: 'Кирило та няня Наташа в паніці...',
    world: 4100,
    startR: 28,
    bossR: 128,
    boss: 'kirill',
    sidekick: 'natasha',     // Наташа поруч із Кирилом
    bossShoots: false,
    sky: ['#7db0e0', '#3a6aa0'],
    grid: 'rgba(255,255,255,0.06)',
    floor: '#5b9a55',
    hue: 285,
    spawns: [
      { type: 'house', count: 30, rMin: 26, rMax: 40 },
      { type: 'tree', count: 30, rMin: 20, rMax: 32 },
      { type: 'building', count: 34, rMin: 50, rMax: 78 },
      { type: 'tower', count: 22, rMin: 70, rMax: 100 },
      { type: 'cloud', count: 26, rMin: 40, rMax: 70 },
    ],
    tips: 'Наташа тримає Кирила за руку. Дожени обох!',
  },
  {
    id: 6,
    name: 'ФІНАЛ — КОСМОС',
    subtitle: 'Останній рубіж: геній Молгелевич',
    world: 4600,
    startR: 34,
    bossR: 150,
    boss: 'molgelevich',
    bossShoots: true,         // стріляє анти-матерією, що зменшує Нікіту
    sky: ['#1a0b33', '#05010f'],
    grid: 'rgba(180,140,255,0.05)',
    floor: '#0a0520',
    hue: 290,
    spawns: [
      { type: 'satellite', count: 30, rMin: 18, rMax: 30 },
      { type: 'star', count: 50, rMin: 10, rMax: 20 },
      { type: 'building', count: 20, rMin: 30, rMax: 50 },
      { type: 'cloud', count: 16, rMin: 40, rMax: 60 },
      { type: 'planet', count: 14, rMin: 70, rMax: 110 },
    ],
    tips: 'Молгелевич стріляє анти-матерією! Ухиляйся, рости й проковтни генія.',
  },
];
